-- =========================
-- Tablas base
-- =========================
CREATE TABLE roles (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name VARCHAR(30) UNIQUE NOT NULL
);

CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name VARCHAR(100) NOT NULL,
                       email VARCHAR(255) UNIQUE NOT NULL,
                       password_hash VARCHAR(255) NOT NULL,
                       created_at TIMESTAMP NOT NULL DEFAULT NOW(),
                       updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE instruments (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             symbol VARCHAR(16) UNIQUE NOT NULL,
                             name   VARCHAR(120) NOT NULL
);

-- =========================
-- Relaciones / tablas puente
-- =========================
CREATE TABLE user_roles (
                            user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                            role_id BIGINT NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
                            PRIMARY KEY (user_id, role_id)
);

CREATE TABLE favorites (
                           user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                           instrument_id BIGINT NOT NULL REFERENCES instruments(id) ON DELETE CASCADE,
                           PRIMARY KEY (user_id, instrument_id)
);

-- =========================
-- Datos de mercado / auditoría
-- =========================
CREATE TABLE price_snapshot (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                instrument_id BIGINT NOT NULL REFERENCES instruments(id) ON DELETE CASCADE,
                                price  NUMERIC(18,6) NOT NULL,
                                open   NUMERIC(18,6),
                                high   NUMERIC(18,6),
                                low    NUMERIC(18,6),
                                volume BIGINT,
                                as_of TIMESTAMP NOT NULL,
                                created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE audit_log (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           action VARCHAR(64) NOT NULL,
                           performed_by VARCHAR(255) NOT NULL,
                           details TEXT,
                           created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- =========================
-- Índices
-- =========================
CREATE INDEX idx_user_roles_user_id      ON user_roles(user_id);
CREATE INDEX idx_user_roles_role_id      ON user_roles(role_id);

CREATE INDEX idx_favorites_user_id       ON favorites(user_id);
CREATE INDEX idx_favorites_instrument_id ON favorites(instrument_id);

CREATE INDEX idx_price_snapshot_instr_id        ON price_snapshot(instrument_id);
CREATE INDEX idx_price_snapshot_instr_id_as_of  ON price_snapshot(instrument_id, as_of);